### ISSUE TITLE
Heroku deployment crashes

### ISSUE THREAD

**Issue by katcosgrove** [alfg/overwatch-api#31]
Hi! I'm trying to use this for a school project, but having issues getting a running copy online. I just used the deploy to Heroku button, and it crashes on launch. Here are the logs:

2017-11-13T17:51:04.731103+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=final301overwatch.herokuapp.com request_id=54307148-bd0a-4ae9-a3b3-06e948886ea2 fwd="209.210.157.165" dyno= connect= service= status=503 bytes= protocol=https
2017-11-13T17:51:05.121829+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=final301overwatch.herokuapp.com request_id=78d7cadf-5db8-434f-9ba1-2e60e6615715 fwd="209.210.157.165" dyno= connect= service= status=503 bytes= protocol=https

If I try to clone it locally, after running npm install and npm start I get this error in terminal:

Error: /Users/kat/codefellows/301/overwatch-api/app/index.js does not exist.
▼ Ready! Listening on: http://0.0.0.0:3000
Mon, 13 Nov 2017 17:56:11 GMT uncaughtException: Cannot read property 'default' of undefined
TypeError: Cannot read property 'default' of undefined
    at Object.server (/Users/kat/codefellows/301/overwatch-api/node_modules/srv-cli/build/cmd/server:26:18)
    at Object.<anonymous> (/Users/kat/codefellows/301/overwatch-api/node_modules/srv-cli/build/srv:132:5)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! overwatch-api@0.2.4 start: `node node_modules/srv-cli/build/srv app/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the overwatch-api@0.2.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kat/.npm/_logs/2017-11-13T17_56_11_227Z-debug.log

**Comment by alfg** [comment]
Hi @katcosgrove, 

Sorry about that. Looks like a recent update to https://github.com/alfg/srv caused this issue. I reverted the srv package back to 0.3.3 as a tempfix until I can properly fix the issue on srv.

Go ahead and clear your node_modules folder and run npm install again. Heroku deploy should also be fixed on your next deploy.

Report back if this solves your issue. 

Thanks!
