### ISSUE TITLE
API package: Cannot find module 'svg-builder'

### ISSUE THREAD

**Issue by rxgx** [alfg/overwatch-api#49]
When I use the `overwatch-api` module in a node script:

```js
const overwatch = require('overwatch-api');

const platform = 'xbl';
const region = 'us';
const tag = 'RXGX';

overwatch.getProfile(platform, region, tag, (error, json) => {
  console.log(error, json);
});
```

I get the error:

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'svg-builder'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/rxgx/Projects/rxgx/overwatch-test/node_modules/overwatch-api/lib/parser/svg.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/rxgx/Projects/rxgx/overwatch-test/node_modules/overwatch-api/lib/parser/profile.js:159:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/rxgx/Projects/rxgx/overwatch-test/node_modules/overwatch-api/lib/parser/index.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

When I add `svg-builder` to the dev dependencies, the error goes away.

**Comment by alfg** [comment]
Good catch! Looks like I forgot to add the svg-builder to `api/package.json`. I'll fix this tonight.

**Comment by alfg** [comment]
Fixed with https://github.com/alfg/overwatch-api/commit/6ac3058cfa278ddfa822749b55193d99f82685f3 and npm published!

Thanks again!
